name: Laravel Production Migrate and Seed on Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate-seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          # extensions: mbstring, pdo, pdo_mysql
          # tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set production environment variables
        run: |
          echo "APP_ENV=production" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations in production
        run: php artisan migrate --force

      - name: Seed database in production
        run: php artisan db:seed --force
